#! /bin/sh

sxhkd &

killall compton 
compton & 

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV 

bspc config border_width         2
bspc config window_gap          20
bspc config focused_border_color "#00aa88"
bspc config normal_border_color "#212121"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Geary desktop='^3' follow=on 
bspc rule -a Firefox desktop='^3' follow=on 
